CREATE TABLE `companies` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`website` text,
	`description` text,
	`logo_url` text,
	`stage` text DEFAULT 'unknown' NOT NULL,
	`sector` text DEFAULT 'other' NOT NULL,
	`subsector` text,
	`geography` text,
	`city` text,
	`founded_year` integer,
	`team_size` integer,
	`funding_total_usd` real,
	`last_funding_date` text,
	`last_funding_amount_usd` real,
	`last_funding_type` text,
	`arr_usd` real,
	`mrr_usd` real,
	`growth_rate_pct` real,
	`status` text DEFAULT 'radar' NOT NULL,
	`source_type` text DEFAULT 'inbound_portal' NOT NULL,
	`source_detail` text,
	`assigned_to` text,
	`ai_pre_score` real,
	`ai_pre_summary` text,
	`pass_reason` text,
	`crunchbase_url` text,
	`linkedin_url` text,
	`angellist_url` text,
	`github_url` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE `contacts` (
	`id` text PRIMARY KEY NOT NULL,
	`company_id` text NOT NULL,
	`name` text NOT NULL,
	`role` text DEFAULT 'founder' NOT NULL,
	`title` text,
	`linkedin_url` text,
	`twitter_url` text,
	`email` text,
	`background` text,
	`education` text,
	`is_founder` integer DEFAULT true NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `outreach` (
	`id` text PRIMARY KEY NOT NULL,
	`company_id` text NOT NULL,
	`contact_id` text,
	`type` text NOT NULL,
	`status` text DEFAULT 'planned' NOT NULL,
	`sent_at` text,
	`replied_at` text,
	`notes` text,
	`template_used` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`contact_id`) REFERENCES `contacts`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `screenings` (
	`id` text PRIMARY KEY NOT NULL,
	`company_id` text NOT NULL,
	`screened_by` text,
	`screening_date` text,
	`score_team` real,
	`score_market` real,
	`score_product` real,
	`score_traction` real,
	`score_business_model` real,
	`score_investment_fit` real,
	`overall_score` real,
	`ai_score_rationale` text,
	`decision` text,
	`decision_rationale` text,
	`meeting_notes` text,
	`ai_summary` text,
	`ai_flags` text,
	`ai_one_pager` text,
	`ic_memo_draft` text,
	`status` text DEFAULT 'queued' NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `signals` (
	`id` text PRIMARY KEY NOT NULL,
	`company_id` text NOT NULL,
	`type` text NOT NULL,
	`title` text NOT NULL,
	`description` text,
	`url` text,
	`source_name` text,
	`published_at` text,
	`detected_at` text NOT NULL,
	`is_read` integer DEFAULT false NOT NULL,
	`sentiment` text DEFAULT 'neutral' NOT NULL,
	`created_at` text NOT NULL,
	FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON UPDATE no action ON DELETE cascade
);
