CREATE TABLE `fund_config` (
	`id` text PRIMARY KEY NOT NULL,
	`org_id` text DEFAULT 'default' NOT NULL,
	`fund_name` text DEFAULT 'My VC Fund' NOT NULL,
	`fund_thesis` text,
	`website` text,
	`target_stages` text DEFAULT '["seed","series_a"]' NOT NULL,
	`target_sectors` text DEFAULT '["fintech","saas","healthtech"]' NOT NULL,
	`target_geographies` text DEFAULT '["IN","US"]' NOT NULL,
	`min_check_usd` integer DEFAULT 500000,
	`max_check_usd` integer DEFAULT 5000000,
	`pre_screen_pass_threshold` integer DEFAULT 40,
	`pre_screen_advance_threshold` integer DEFAULT 70,
	`score_weights` text DEFAULT '{"team":1.5,"market":1.0,"product":1.0,"traction":1.0,"business_model":1.0,"investment_fit":1.5}' NOT NULL,
	`analyst_review_sla_hours` integer DEFAULT 72,
	`ic_review_sla_hours` integer DEFAULT 168,
	`analyst_emails` text DEFAULT '[]' NOT NULL,
	`ic_member_emails` text DEFAULT '[]' NOT NULL,
	`partner_emails` text DEFAULT '[]' NOT NULL,
	`primary_currency` text DEFAULT 'USD',
	`date_format` text DEFAULT 'MMM d, yyyy',
	`timezone` text DEFAULT 'Asia/Kolkata',
	`auto_pass_email_enabled` integer DEFAULT false,
	`auto_ack_email_enabled` integer DEFAULT false,
	`resend_api_key` text,
	`created_at` text,
	`updated_at` text
);
